@MovieApi_Refactor_HostAddress = http://localhost:5088
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InhhdmlkaWF6Iiwic3ViIjoieGF2aWRpYXoiLCJqdGkiOiI2OTAyNGU3ZiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODgiLCJodHRwczovL2xvY2FsaG9zdDo3MDExIl0sIm5iZiI6MTc4OTczMjMzMywiZXhwIjoxNzk3NTk0NzMzLCJpYXQiOjE3ODk3MzIzMzMsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.F0fzofeFOa9Oh5Pciz5BX6NOjOlt_bhgZRl6E4k8jiU

### Movies GET all
GET {{MovieApi_Refactor_HostAddress}}/movies/
Accept: application/json

### Movie GET
GET {{MovieApi_Refactor_HostAddress}}/movies/1
Accept: application/json

### Movie Post
POST {{MovieApi_Refactor_HostAddress}}/movies/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "title":"Men In Black",
    "year":"2000",
    "actorsId": [1,2]
  }

### Movie Put
PUT {{MovieApi_Refactor_HostAddress}}/movies/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "title":"Men In Black",
    "year":"2002",
    "actorsId": [1,2]
}

### Movie DELETE
DELETE {{MovieApi_Refactor_HostAddress}}/movies/1
Accept: application/json
Authorization: Bearer {{Token}}

### Actors GET all
GET {{MovieApi_Refactor_HostAddress}}/actors/
Accept: application/json

### Actor GET
GET {{MovieApi_Refactor_HostAddress}}/actors/1
Accept: application/json

### Actor Post
POST {{MovieApi_Refactor_HostAddress}}/actors/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "firstName": "Will",
    "lastName": "Smith",
    "birthYear": 1968,
    "moviesId": [1]
}

### Actor Put
PUT {{MovieApi_Refactor_HostAddress}}/actors/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "firstName": "Keanu",
    "lastName": "Reeves",
    "birthYear": 1964,
    "moviesId": [1, 2]
}

### Actor DELETE
DELETE {{MovieApi_Refactor_HostAddress}}/actors/1
Accept: application/json
Authorization: Bearer {{Token}}

### Reviews GET all
GET {{MovieApi_Refactor_HostAddress}}/reviews/
Accept: application/json

### Review GET 
GET {{MovieApi_Refactor_HostAddress}}/reviews/1
Accept: application/json

### Review Post
POST {{MovieApi_Refactor_HostAddress}}/reviews/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "rating": 6.5,
    "text": "Rolig men ytlig uppföljare.",
    "movieId": 1
}

### Review Put
PUT {{MovieApi_Refactor_HostAddress}}/reviews/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "rating": 8.7,
    "text": "Genredefinierande sci-fi.",
    "movieId": 1
}

### Review DELETE
DELETE {{MovieApi_Refactor_HostAddress}}/reviews/1
Accept: application/json
Authorization: Bearer {{Token}}
