@Api_HostAddress = http://localhost:5088
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InhhdmlkaWF6Iiwic3ViIjoieGF2aWRpYXoiLCJqdGkiOiIxZmUyODQ2MSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODgiLCJodHRwczovL2xvY2FsaG9zdDo3MDExIl0sIm5iZiI6MTc5MDE1NTg3NiwiZXhwIjoxNzk4MDE4Mjc2LCJpYXQiOjE3OTAxNTU4NzcsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.16qLB35hRvu9985JMsI5yN-dzHlmy9cJT6acZbueyb8
@TokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InhhdmlkaWF6Iiwic3ViIjoieGF2aWRpYXoiLCJqdGkiOiJhOTcwM2FhMCIsInJvbGUiOiJBZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODgiLCJodHRwczovL2xvY2FsaG9zdDo3MDExIl0sIm5iZiI6MTc5MDE1NTg5OCwiZXhwIjoxNzk4MDE4Mjk4LCJpYXQiOjE3OTAxNTU4OTksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.epFgOh3rgWV9PJG-EfYeRGRP4EutE7PzRbhkBGy3c5o

### Movies GET all
GET {{Api_HostAddress}}/movies/
Accept: application/json

### Movie GET
GET {{Api_HostAddress}}/movies/1
Accept: application/json

### Movie Post
POST {{Api_HostAddress}}/movies/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "title":"Men In Black",
    "year":"2000",
    "actorsId": [1,2]
  }

### Movie Put
PUT {{Api_HostAddress}}/movies/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "title":"Men In Black",
    "year":"2002",
    "actorsId": [1,2]
}

### Movie DELETE utan Admin-roll (ska ge 403 Forbidden)
DELETE {{Api_HostAddress}}/movies/1
Accept: application/json
Authorization: Bearer {{Token}}

### Movie DELETE med Admin-roll (ska funka) 
DELETE {{Api_HostAddress}}/movies/1
Accept: application/json
Authorization: Bearer {{TokenAdmin}}

### Actors GET all
GET {{Api_HostAddress}}/actors/
Accept: application/json

### Actor GET
GET {{Api_HostAddress}}/actors/1
Accept: application/json

### Actor Post
POST {{Api_HostAddress}}/actors/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "firstName": "Will",
    "lastName": "Smith",
    "birthYear": 1968,
    "moviesId": [1]
}

### Actor Put
PUT {{Api_HostAddress}}/actors/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "firstName": "Keanu",
    "lastName": "Reeves",
    "birthYear": 1964,
    "moviesId": [1, 2]
}

### Actor DELETE utan Admin-roll (ska ge 403 Forbidden)
DELETE {{Api_HostAddress}}/actors/1
Accept: application/json
Authorization: Bearer {{Token}}

### Actor DELETE med Admin-roll (ska funka) 
DELETE {{Api_HostAddress}}/actors/1
Accept: application/json
Authorization: Bearer {{TokenAdmin}}

### Reviews GET all
GET {{Api_HostAddress}}/reviews/
Accept: application/json

### Review GET 
GET {{Api_HostAddress}}/reviews/1
Accept: application/json

### Review Post
POST {{Api_HostAddress}}/reviews/
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "rating": 6.5,
    "text": "Rolig men ytlig uppföljare.",
    "movieId": 1
}

### Review Put
PUT {{Api_HostAddress}}/reviews/1
Content-type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
    "rating": 8.7,
    "text": "Genredefinierande sci-fi.",
    "movieId": 1
}

### Review DELETE utan Admin-roll (ska ge 403 Forbidden)
DELETE {{Api_HostAddress}}/reviews/1
Accept: application/json
Authorization: Bearer {{Token}}

### Review DELETE med Admin-roll (ska funka) 
DELETE {{Api_HostAddress}}/reviews/1
Accept: application/json
Authorization: Bearer {{TokenAdmin}}
